export const initialState = {
	activeTile: null,
	currentLayerIndex: 0,
	defaultZoom: 1,
	focusedItemID: null,
	isPathfindingGridVisible: false,
	isSaving: false,
	layers: [{}],
	name: '',
	openItems: {},
	pfgridStacks: {},
	selection: null,
	tool: 'marquee',
	zoom: 1,
}
