export const initialState = {
	activeTile: null,
	currentLayerIndex: 0,
	defaultZoom: 1,
	destinations: {},
	notifications: [],
	focusedItemID: null,
	isDestinationsVisible: true,
	isPathfindingGridVisible: false,
	isStartingPositionVisible: true,
	isSaving: false,
	layers: [{}],
	name: '',
	openItems: {},
	pfgridStacks: {},
	selection: null,
	startingPosition: null,
	tool: 'marquee',
	zoom: 1,
}
